spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bunnyland
    username: bunny
    password: bunny123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

security:
  jwt:
    access:
      secret: ${ACCESS_SECRET:change-me}
      ttl-seconds: 900
    refresh:
      secret: ${REFRESH_SECRET:change-me-too}
      ttl-seconds: 604800
