spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bunnyland
    username: bunny
    password: bunny123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
